INSERT OR REPLACE INTO suppliers (id, name, group_name, currency, supplier_folder)
VALUES
(1, 'International Parts Trading NED', 'GER3', 'EUR', 'IPT_NED'),
(2, 'M Auto Euro', 'POL', 'PLN', 'AUTO_EURO'),
(3, 'M Auto Fus BMW', 'POL2', 'PLN', 'AUTO_FUS_BMW'),
(4, 'M Auto Fus FCA', 'POL2', 'PLN', 'AUTO_FUS_FCA'),
(5, 'M Auto Land', 'POL', 'EUR', 'AUTO_LAND'),
(6, 'M Auto Partner', 'POL', 'PLN', 'AUTO_PARTNER'),
(7, 'M Auto Partner Gdansk', 'POL', 'PLN', 'AUTO_PARTNER_GDANSK'),
(8, 'M Auto Zatoka', 'POL', 'PLN', 'AUTO_ZATOKA'),
(9, 'M AUTO-FRANCE', 'POL', 'PLN', 'AUTO_FRANCE'),
(10, 'M Autohaus Otto', 'POL2', 'PLN', 'AUTO_HAUS_OTTO'),
(11, 'M AutoLine', 'GER', 'EUR', 'AUTO_LINE'),
(12, 'M AutoPlaza FORD', 'POL 2', 'PLN', 'AUTO_PLAZA_FORD'),
(13, 'M AVTONOVA-D', 'GER 2', 'EUR', 'AUTO_NOVA_D'),
(14, 'M Bronowski', 'POL', 'PLN', 'BRONOWSKI'),
(15, 'M Caffaro', 'POL', 'PLN', 'CAFFARO'),
(16, 'M Distrigo PSA', 'POL 2', 'PLN', 'DISTRIGO'),
(17, 'M E-MOTO', 'POL', 'PLN', 'EMOTO'),
(18, 'M EBC Polska', 'POL', 'PLN', 'EBC'),
(19, 'M Elit', 'POL', 'PLN', 'ELIT'),
(20, 'M Euro-Kas Volvo', 'POL 2', 'PLN', 'EURO_KAS_VOLVO'),
(21, 'M EUROESTCAR', 'POL 2', 'EUR', 'EURO_EST_KAR'),
(22, 'M Gordon', 'POL', 'PLN', 'GORDON'),
(23, 'M Grupa Zdunek', 'POL 2', 'PLN', 'GRUPA_ZDUNEK'),
(24, 'M Hart Sp. z o.o.', 'POL', 'PLN', 'HART'),
(25, 'M Inter Cars', 'POL', 'PLN', 'INTER_CARS'),
(26, 'M Inter-Team', 'POL', 'PLN', 'INTER_TEAM'),
(27, 'M INTERVITO', 'POL', 'PLN', 'INTERVITO'),
(28, 'M JD Kulej', 'POL 2', 'PLN', 'JD_KULEJ'),
(29, 'M Karlik Group', 'POL 2', 'PLN', 'KARLIK_GROUP'),
(32, 'M Kris-Auto', 'POL', 'PLN', 'KRIS_AUTO'),
(33, 'M Krotoski Nadarzyn VAG', 'POL 2', 'PLN', 'KROTOSKI_VAG'),
(34, 'M Lion Motors Katowice', 'POL 2', 'PLN', 'LION_MOTORS'),
(35, 'M Mapco', 'GER', 'EUR', 'MAPCO'),
(36, 'M Maxauto Baltic', 'GER 2', 'EUR', 'MAXAUTO_BALTIC'),
(37, 'M Mercedes-Benz Warszawa', 'POL 2', 'PLN', 'MERCEDES_BENZ_WARSZAWA'),
(38, 'M MM Cars', 'POL 2', 'PLN', 'MM_CARS'),
(39, 'M Moto Profil', 'POL', 'PLN', 'MOTOPROFIL'),
(40, 'M Motogama', 'POL', 'PLN', 'MOTOGAMA'),
(41, 'M MOTORES', 'POL', 'PLN', 'MOTORES'),
(42, 'M Motorol', 'POL', 'PLN', 'MOTOROL'),
(43, 'M Odyssey MAZDA', 'POL 2', 'PLN', 'ODYSSEY_MAZDA'),
(44, 'M Odyssey NISSAN', 'POL 2', 'PLN', 'ODYSSEY_NISSAN'),
(45, 'M ORAP', 'GER 2', 'EUR', 'ORAP'),
(46, 'M ORAP Bentley', 'GER 2', 'EUR', 'ORAP_BENTLEY'),
(47, 'M ORAP Stock', 'GER 2', 'EUR', 'ORAP_STOCK'),
(48, 'M Paketo', 'POL', 'PLN', 'PAKETO'),
(49, 'M Plichta', 'POL 2', 'PLN', 'PLICHTA'),
(50, 'M Potak', 'POL 2', 'PLN', 'POTAK'),
(51, 'M Renault Auto Drap', 'POL 2', 'PLN', 'AUTO_DRAP'),
(52, 'M Toyota Auto Park', 'POL 2', 'PLN', 'TOYOTA_AUTO_PARK'),
(53, 'M Toyota Warszawa Wola CCC', 'POL 2', 'PLN', 'TOYOTA_WARSZAWA_WOLA_CCC'),
(54, 'M VanKing', 'POL', 'PLN', 'VANKING'),
(54, 'M Voyager Group', 'POL 2', 'PLN', 'VOYAGER_GROUP'),
(54, 'MEX 15', 'EMEX', 'USD', 'MEX15'),
(54, 'MEX 21', 'EMEX', 'USD', 'MEX21'),
(54, 'MEX 7', 'EMEX', 'USD', 'MEX7'),
(54, 'Plus Parts NED', 'GER 3', 'EUR', 'PLUS_PARTS_NED'),
(55, 'M Rodon', 'POL', 'PLN', 'RODON'),
(56, 'MNK Stock', 'POL', 'PLN', 'MNK_STOCK'),
(57, 'MNK Zwrot', 'POL', 'PLN', 'MNK_ZWROT'),
(58, 'M Moto-Hurt S.A.', 'ZIP', 'PLN', 'MOTO_HURT'),
(59, 'M Inter Parts', 'ZIP', 'EUR', 'INTER_PARTS');
