INSERT OR REPLACE INTO rename_files (id, file_id, old_file_name, new_file_name)
VALUES
(1, 21, '29366_ce.csv', 'autopartner_gdansk_data.csv'),
(2, 13, 'STANY54672.csv', 'emoto_data.csv'),
(3, 11, '96285_CN.csv', 'hart_cn.csv'),
(4, 9, '96285_cross.csv', 'hart_cross.csv'),
(5, 8, '96285_kth.csv', 'hart_data.csv'),
(6, 12, '96285_kth+wgh.csv', 'hart_weight.csv'),
(7, 10, '96285_kz.csv', 'hart_deposit.csv'),
(8, 7, '96285_PriceList_PLN.csv', 'hart_prices.csv'),
(9, 7, '96285_Quantity.csv', 'hart_quantity.csv'),
(10, 22, '65232_ce.csv', 'interparts_data.csv'),
(11, 4, 'it84262.csv', 'interteam_data.csv'),
(12, 6, '08525.mnk.cennik.csv', 'motorol_data.csv'),
(13, 27, 'Priceoem1.txt', 'orap_price_oem1.txt'),
(14, 26, 'Priceoem2.txt', 'orap_price_oem2.txt'),
(15, 25, 'Priceoem4.txt', 'orap_price_oem4.txt'),
(16, 52, 'NISSAN.txt', 'orap_nissan.txt'),
(17, 50, 'Price Febi+BluePrint.txt', 'orap_price_febi_blueprint.txt'),
(18, 48, 'Price FIAT Chrysler.txt', 'orap_price_fiat_chrysler.txt'),
(19, 49, 'Price FIATChrysler_L.txt', 'orap_price_fiat_chrysler_l.txt'),
(20, 47, 'PRICE FORD_Long.txt', 'orap_price_ford_long.txt'),
(21, 46, 'Price GM_long.txt', 'orap_price_gm_long.txt'),
(22, 45, 'Price Honda_long.txt', 'orap_price_honda_long.txt'),
(23, 44, 'Price JAGUAR.txt', 'orap_price_jaguar.txt'),
(24, 43, 'Price Land_Rover.txt', 'orap_price_land_rover.txt'),
(25, 42, 'Price PSA.txt', 'orap_price_psa.txt'),
(26, 41, 'Price Volvo.txt', 'orap_price_volvo.txt'),
(27, 40, 'Price_FORD.txt', 'orap_price_ford.txt'),
(28, 39, 'Price_HONDA.txt', 'orap_price_honda.txt'),
(29, 38, 'Price_MAN.txt', 'orap_price_man.txt'),
(30, 37, 'Price_Mazda.txt', 'orap_price_mazda.txt'),
(31, 36, 'Price_MB.txt', 'orap_price_mb.txt'),
(32, 35, 'Price_Mitsubishi.txt', 'orap_price_mitsubishi.txt'),
(33, 34, 'Price_Porsche.txt', 'orap_price_porsche.txt'),
(34, 33, 'Price_Renault.txt', 'orap_price_renault.txt'),
(35, 30, 'Price_Toyota.txt', 'orap_price_toyota.txt'),
(36, 29, 'Price_VAG.txt', 'orap_price_vag.txt'),
(37, 28, 'PriceBMWALL.txt', 'orap_price_bmwall.txt'),
(38, 31, 'Price_Suzuki.txt', 'orap_price_suzuki.txt'),
(39, 32, 'Price_Subaru.txt', 'orap_price_subaru.txt'),
(40, 6, 'oapnal.xlsx', 'orap_oapnal.xlsx'),
(41, 18, '57765_01.csv', 'rodon_data.csv');