---
build: dev
version: 1.0.0
suppliers:
  bronowski:
    name: bronowski
    status: true
    updated: 00-00-0000
    download_files: true
    download_type: mail
    download_file_name: bronowski_data.xls
    download_params:
      sender: bronek@bronowski.pl
      subject: Odbiorca 71233712 Oferta towarowa
    multiple: false
    files:
      data:
        file_type: excel
        mod_time: null
        url: ftp://suppliers:zR3uB2aJ3m@138.201.56.185/bronowski/export.xls
        header: false
  vanking:
    name: vanking
    status: true
    updated: 00-00-0000
    download_files: true
    download_type: mail
    download_file_name: euroestcar_data.xlsx
    download_params:
      sender: raporty@vanking.com.pl
      subject: null
    multiple: false
    files:
      data:
        file_type: excel
        mod_time: null
        url: ftp://suppliers:zR3uB2aJ3m@138.201.56.185/vanking/export.xlsx
        header: false
  euroestcar:
    name: euroestcar
    status: true
    updated: 00-00-0000
    download_files: true
    download_type: mail
    download_file_name: vanking_data.xlsx
    download_params:
      sender: margareta.peptenaru@euroestcar.ro
      subject: STOCK EEC
    multiple: false
    files:
      data:
        file_type: excel
        mod_time: null
        url: ftp://suppliers:zR3uB2aJ3m@138.201.56.185/euroestcar/export.xlsx
        type: excel
        header: false
  direct24:
    name: direct_24
    status: true
    updated: 00-00-0000
    download_files: true
    download_type: url
    download_file_name: direct_24.zip
    download_params:
      url: https://direct24.com.ua/exporter/files/d0553d0b7205c12be91588a0d134574cc364771c
    multiple: false
    files:
      data:
        file_type: csv
        mod_time: null
        url: ftp://suppliers:zR3uB2aJ3m@138.201.56.185/euroestcar/export.xlsx
        header: false


