from api.Services.Loader.APILoader import downloadFileFromAPI
from api.SupplierScripts.Direct24.Direct24 import direct24_to_db
from api.SupplierScripts.InterCars.InterCars import intercars_to_db
from api.SupplierScripts.Orap.Orap import orap_to_db
from api.SupplierScripts.Autopartner.Autopartner import autopartner_to_db
from api.SupplierScripts.AutoEuro.AutoEuro import autoeuro_to_db
from api.SupplierScripts.AutoFusBmw.AutoFusBmw import autofusbmw_to_db
from api.SupplierScripts.AutoLand.AutoLand import autoland_to_db
from api.SupplierScripts.Autopartner.Autopartner import autopartner_to_db
from api.SupplierScripts.AutopartnerGdansk.AutopartnerGdansk import autopartner_gdansk_to_db
from api.SupplierScripts.Bronowski.Bronowski import bronowski_to_db
from api.SupplierScripts.Direct24.Direct24 import direct24_to_db
from api.SupplierScripts.Elit.Elit import elit_to_db
from api.SupplierScripts.Emoto.Emoto import emoto_to_db
from api.SupplierScripts.EuroEstCar.EuroEstCar import euroestcar_to_db
from api.SupplierScripts.Gordon.Gordon import gordon_to_db
from api.SupplierScripts.Hart.Hart import hart_to_db
from api.SupplierScripts.InterCars.InterCars import intercars_to_db
from api.SupplierScripts.InterTeam.InterTeam import inter_team_to_db
from api.SupplierScripts.Intervito.Intervito import intervito_to_db
from api.SupplierScripts.KrisAuto.KrisAuto import krisauto_to_db
from api.SupplierScripts.Motogama.Motogama import motogama_to_db
from api.SupplierScripts.Motoprofil.Motoprofil import motoprofil_to_db
from api.SupplierScripts.Motorol.Motorol import motorol_to_db
from api.SupplierScripts.Paketo.Paketo import paketo_to_db
from api.SupplierScripts.Rodon.Rodon import rodon_to_db
from api.SupplierScripts.Vanking.Vanking import vanking_to_db
from api.SupplierScripts.Zdunek.Zdunek import zdunek_to_db
