from __init__ import *
from Services.Email.EmailSender import EmailSender
from SupplierScripts.Ronax.Ronax import *

if __name__ == '__main__':
    ronax_to_db()
    #sender = EmailSender()
    #sender.send("k.pylinskyi@gmail.com", 'Subject: SubSub\n\n<h1>Huy huy regina</h1>')
    #sender.send("polinap5411@gmail.com", 'Subject: SubSub\n\n<h1>Huy huy regina</h1>')
    autopartner_to_db()
    voyagerGroup_to_db()
    autoland_to_db()
    intercars_to_db()
    autofusbmw_to_db()
    autoeuro_to_db()
    hart_to_db()
    zdunek_to_db()
    # euroestcar_to_db()
    vanking_to_db()
    bronowski_to_db()
    # direct24_to_db() # ne rabotaet
    intervito_to_db()
    autopartner_gdansk_to_db()
    emoto_to_db()
    gordon_to_db()
    motorol_to_db()
    paketo_to_db()
    rodon_to_db()
    motogama_to_db()
    elit_to_db()
    inter_team_to_db()
    motorol_to_db()
    motoprofil_to_db()
    krisauto_to_db()
    # DbService.get_db_backup()
