
from __init__ import *

if __name__ == '__main__':
    orap_to_db()
    materom_to_db()
    intervito_to_db()
    direct24_to_db()
    intercars_to_db()
    autofusbmw_to_db()
    autoeuro_to_db()
    hart_to_db()
    zdunek_to_db()
    euroestcar_to_db()
    autoland_to_db()
    vanking_to_db()
    bronowski_to_db()
    # autopartner_to_db()  # ne korektnye znachenia
    autopartner_gdansk_to_db()
    emoto_to_db()
    gordon_to_db()
    motorol_to_db()
    paketo_to_db()
    rodon_to_db()
    motogama_to_db()
    elit_to_db()
    inter_team_to_db()
    motoprofil_to_db()
    krisauto_to_db()
    # DbService.get_db_backup()
